"""configs/dumps/*.flow.yaml are what kalfa check --dump prints for 01 and tidy: text equality, never hand written."""

import json
import sys
import warnings

import pytest
from ruamel.yaml import YAML

import kalfa  # noqa: F401
from conftest import ROOT
from kalfa.api import check
from kalfa.cli import main

sys.path.insert(0, str(ROOT / "tests" / "fixtures"))
from regenerate_dumps import TARGETS, TOLERATED, render  # noqa: E402


def plain(value):
    return json.loads(json.dumps(value, sort_keys=True, default=repr))


@pytest.mark.parametrize("config, dump, recipe", TARGETS)
def test_dump_text_is_current(config, dump, recipe):
    assert (ROOT / "configs" / "dumps" / dump).read_text() == render(config, recipe)


@pytest.mark.parametrize("config, dump, recipe", TARGETS)
def test_generated_document_equals_the_dump(config, dump, recipe):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        prepared = check([str(ROOT / config)])
    assert all(problem.kind in TOLERATED for problem in prepared.errors)
    generated = YAML(typ="safe").load(prepared.dump())
    expected = YAML(typ="safe").load((ROOT / "configs" / "dumps" / dump).read_text())
    assert set(generated) == {"components", "blocks", "flow"}
    assert plain(generated) == plain(expected)


def test_01_dump_shape():
    expected = YAML(typ="safe").load((ROOT / "configs" / "dumps" / "01.flow.yaml").read_text())
    flow = expected["flow"]
    assert list(flow) == ["outputs", "data", "models", "optimizers", "training", "after"]
    body = flow["training"]["epochs"]["loop"]["body"]
    assert list(body) == ["effects", "turn", "evaluate_valid", "evaluate_test", "metrics", "rules_0", "rule_1", "rule_2",
                          "rule_3", "rules_ruled", "stop", "checkpoint", "log"]
    assert expected["components"]["triggers"]["to_huber"]["uri"] == "/trigger/kalfa/after_turn"
    assert body["turn"]["params"]["params"] == {}
    assert body["checkpoint"]["params"]["policy"] == {"uri": "/checkpoint/kalfa/best", "params": {"monitor": "val/rmse"}}
    text = (ROOT / "configs" / "dumps" / "01.flow.yaml").read_text()
    assert text.startswith("# Generated by kalfa") and "# implicit: device" in text
    assert "parts *_metrics: test_metrics, train_metrics, valid_metrics" in text


def test_cli_dump_prints_the_document(workdir, config_01, capsys):
    assert main(["check", config_01, "--dump"]) == 0
    out = capsys.readouterr().out
    document = YAML(typ="safe").load(out.split("---\n", 1)[1])
    assert list(document) == ["components", "blocks", "flow"]
    assert "# implicit: device" in out
