import json
import warnings

import pytest
from ruamel.yaml import YAML

import regenerate
from helpers import ROOT, example, examples


def plain(value):
    return json.loads(json.dumps(value, sort_keys=True, default=repr))


def golden(kind, name, suffix):
    return YAML(typ="safe").load((ROOT / "tests" / "golden" / kind / f"{name}.{suffix}.yaml").read_text())


@pytest.mark.parametrize("name", examples())
def test_the_dump_is_the_compiled_flow(name):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        prepared = regenerate.prepared_of(name)
    generated = YAML(typ="safe").load(prepared.dump())
    assert set(generated) == {"components", "blocks", "flow"}
    assert plain(generated) == plain(golden("dumps", name, "flow"))


@pytest.mark.parametrize("name", examples())
def test_the_recipe_is_the_driver_document(name):
    from cirak.registry import registry

    from kalfa.config import load_surface
    from kalfa.driver import recipe

    surface = load_surface([example(name)])
    assert surface.errors == []
    document = recipe(surface.data, registry, surface.aliases)
    expected = golden("recipes", name, "recipe")
    assert expected.pop("include") == ["../../../src/kalfa/contract.yaml"]
    assert plain(document) == plain(expected)
    assert list(document) == ["losses", "metrics", "triggers", "plots", "calibrate", "checkpoint", "blocks", "flow"]
    assert list(document["flow"]) == ["outputs", "data", "models", "optimizers", "training", "after"]


def test_the_shape_of_the_regression_dump():
    expected = golden("dumps", "01_mlp_regression", "flow")
    flow = expected["flow"]
    assert list(flow) == ["outputs", "data", "models", "optimizers", "training", "after"]
    body = flow["training"]["epochs"]["loop"]["body"]
    assert list(body) == ["effects", "turn", "evaluate_valid", "evaluate_test", "metrics", "rules_0", "rule_1",
                          "rule_2",
                          "rule_3", "rules_ruled", "stop", "checkpoint", "log"]
    assert expected["components"]["triggers"]["to_huber"]["uri"] == "/trigger/kalfa/after_turn"
    assert body["turn"]["params"]["params"] == {}
    assert body["checkpoint"]["params"]["policy"] == "@checkpoint"
    assert expected["components"]["checkpoint"] == {"uri": "/checkpoint/kalfa/best",
                                                    "params": {"monitor": "val/rmse"}}
    text = (ROOT / "tests" / "golden" / "dumps" / "01_mlp_regression.flow.yaml").read_text()
    assert text.startswith("# Generated by kalfa") and "# implicit: device" in text
    assert "parts *_metrics: test_metrics, train_metrics, valid_metrics" in text


def test_the_alad_recipe_details():
    from cirak.registry import registry

    from kalfa.config import load_surface
    from kalfa.driver import recipe

    surface = load_surface([example("alad")])
    document = recipe(surface.data, registry, surface.aliases)
    adv_d = document["losses"]["adv_d"]["params"]["objective"]
    assert adv_d["params"]["criterion"] == {"uri": "/criterion/kalfa/bce_logits"}
    assert document["metrics"]["auroc"]["uri"] == "/adapter/kalfa/metric"
    assert document["triggers"] == {}
    params = document["flow"]["models"]["params"]
    assert [item["name"] for item in params["trained_items"]] == ["encoder", "generator", "dxz", "dxx", "dzz"]
    assert params["composite_items"] == [{"name": "anomaly_score"}]
    assert document["blocks"]["mlp"]["graph"]["h"] == {"block": "mlp_hidden", "params": {"width": "$width$"},
                                                        "inputs": ["a0"], "repeat": "$depth$"}
    assert document["blocks"]["encoder"]["spec"][0] == {"block": "mlp", "params": {"in_features": 6, "out_features": 64,
                                                                                   "width": 64, "depth": 2}}
    optimizers = document["flow"]["optimizers"]["params"]["optimizer_items"]
    assert [item["name"] for item in optimizers] == ["g", "d"]
    assert optimizers[0]["models"] == {"encoder": "encoder", "generator": "generator"}
    data = document["flow"]["data"]["params"]
    assert data["transform_pre"] == [{"uri": "/transform/kalfa/filter",
                                      "params": {"query": "(is_anomaly > -4) & (is_anomaly < 4)"}}]
    assert data["set_transforms"]["train"]["transforms"] == [{"uri": "/transform/kalfa/filter",
                                                              "params": {"query": "is_anomaly == 0"}}]
    assert data["set_transforms"]["valid"]["transforms"] == []
    assert data["prep"]["params"]["drop"] == ["xx6", "xx7"]
    assert document["checkpoint"] == {}
