"""Regenerate configs/dumps/*.flow.yaml: what ``kalfa check <config> --dump`` prints for 01 and tidy.

The dump is the flow the templates of src/kalfa/templates/kalfa.yaml open for the driver document
(configs/dumps/<name>.recipe.yaml), annotated with tezgah's resolution. cirak's fixture copies are kept equal
to these files. Never written by hand.

    uv run python tests/fixtures/regenerate_dumps.py
"""

import sys
import warnings
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests" / "plugins"))

import cirak  # noqa: E402
import kalfa  # noqa: E402
from kalfa.api import check  # noqa: E402

TARGETS = (("configs/01_mlp_regression.yaml", "01.flow.yaml", "01.recipe.yaml"),
           ("examples/alad/config.yaml", "tidy.flow.yaml", "tidy.recipe.yaml"),
           ("configs/02_mlp_classification.yaml", "02.flow.yaml", "02.recipe.yaml"),
           ("configs/03_timeseries_window.yaml", "03.flow.yaml", "03.recipe.yaml"),
           ("configs/11_kfold_cv.yaml", "11.flow.yaml", "11.recipe.yaml"),
           ("configs/12_resume.yaml", "12.flow.yaml", "12.recipe.yaml"),
           ("configs/05_autoencoder.yaml", "05.flow.yaml", "05.recipe.yaml"),
           ("configs/06_vae_loss_dynamics.yaml", "06.flow.yaml", "06.recipe.yaml"),
           ("configs/04_cnn_images.yaml", "04.flow.yaml", "04.recipe.yaml"),
           ("configs/13_distillation.yaml", "13.flow.yaml", "13.recipe.yaml"),
           ("configs/07_wgan_gp.yaml", "07.flow.yaml", "07.recipe.yaml"),
           ("configs/08_ddpm.yaml", "08.flow.yaml", "08.recipe.yaml"),
           ("configs/09_simclr.yaml", "09.flow.yaml", "09.recipe.yaml"),
           ("configs/10_char_lm.yaml", "10.flow.yaml", "10.recipe.yaml"),
           ("configs/14_sweep_grid.yaml", "14.flow.yaml", "14.recipe.yaml"))
DUMPS = ROOT / "configs" / "dumps"
TOLERATED = ("source_missing", "weights_run_missing")


def header(config, recipe) -> str:
    return (f"# Generated by kalfa {kalfa.__version__} (cirak {cirak.__version__}) from {config}: kalfa check --dump, "
            f"the flow the\n"
            f"# templates of src/kalfa/templates/kalfa.yaml open for the driver document configs/dumps/{recipe}.\n"
            f"# Regenerate with: uv run python tests/fixtures/regenerate_dumps.py\n"
            f"# Sections: components (the recipe's component tables), blocks (spec and graph blocks as templates;\n"
            f"# the flow blocks are opened inside flow), flow (the expanded flow with every output written out;\n"
            f"# the comments are tezgah's resolution: implicit bindings, pattern matches, derived reads and exports).\n")


def render(config, recipe) -> str:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        prepared = check([str(ROOT / config)])
    errors = [problem for problem in prepared.errors if problem.kind not in TOLERATED]
    if errors:
        raise SystemExit("\n".join(f"{config}: [{problem.kind}] {problem.message}" for problem in errors))
    text = prepared.dump()
    if text is None:
        raise SystemExit(f"{config}: the flow could not be compiled")
    return header(config, recipe) + text


def main() -> None:
    for config, dump, recipe in TARGETS:
        (DUMPS / dump).write_text(render(config, recipe))
        print(f"wrote configs/dumps/{dump}")


if __name__ == "__main__":
    main()
