"""Regenerate the driver documents of configs/dumps: 01.recipe.yaml and tidy.recipe.yaml.

They are what kalfa.driver.recipe produces for configs/01_mlp_regression.yaml and examples/alad/config.yaml, written as
standalone cirak recipes (the include points at the template). cirak's tests copy them as fixtures with
``include: [kalfa.yaml]`` and regenerate the dumps from them. Never written by hand.

    uv run python tests/fixtures/regenerate_recipes.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests" / "plugins"))

import kalfa  # noqa: E402
from kalfa.config import load_surface  # noqa: E402
from kalfa.driver import recipe  # noqa: E402
from kalfa.recipe import recipe_text  # noqa: E402

TARGETS = (("configs/01_mlp_regression.yaml", "01.recipe.yaml"), ("examples/alad/config.yaml", "tidy.recipe.yaml"),
           ("configs/02_mlp_classification.yaml", "02.recipe.yaml"), ("configs/03_timeseries_window.yaml", "03.recipe.yaml"), ("configs/11_kfold_cv.yaml", "11.recipe.yaml"),
           ("configs/12_resume.yaml", "12.recipe.yaml"), ("configs/05_autoencoder.yaml", "05.recipe.yaml"), ("configs/06_vae_loss_dynamics.yaml", "06.recipe.yaml"), ("configs/04_cnn_images.yaml", "04.recipe.yaml"), ("configs/13_distillation.yaml", "13.recipe.yaml"), ("configs/07_wgan_gp.yaml", "07.recipe.yaml"), ("configs/08_ddpm.yaml", "08.recipe.yaml"), ("configs/09_simclr.yaml", "09.recipe.yaml"),
           ("configs/10_char_lm.yaml", "10.recipe.yaml"), ("configs/14_sweep_grid.yaml", "14.recipe.yaml"))
DUMPS = ROOT / "configs" / "dumps"
INCLUDE = "../../src/kalfa/templates/kalfa.yaml"


def header(config) -> str:
    return (f"# Generated by kalfa {kalfa.__version__} from {config}: the driver document kalfa.driver.recipe produces,\n"
            f"# the one the templates of src/kalfa/templates/kalfa.yaml open. Not written by hand; regenerate with:\n"
            f"#   uv run python tests/fixtures/regenerate_recipes.py\n"
            f"# cirak's fixture copy replaces the include with kalfa.yaml and regenerates configs/dumps/*.flow.yaml.\n")


def document(config) -> dict:
    surface = load_surface([str(ROOT / config)])
    errors = [problem for problem in surface.problems if problem.severity == "error"]
    if errors:
        raise SystemExit("\n".join(f"{config}: [{problem.kind}] {problem.message}" for problem in errors))
    return recipe(surface.data, aliases=surface.aliases)


def render(config) -> str:
    return header(config) + f"include: [{INCLUDE}]\n" + recipe_text(document(config))


def main() -> None:
    for config, name in TARGETS:
        (DUMPS / name).write_text(render(config))
        print(f"wrote configs/dumps/{name}")


if __name__ == "__main__":
    main()
