import argparse
import importlib.util
import inspect
import json
import os
import shutil
import sys
import tempfile
import warnings
from pathlib import Path

import cirak
from cirak.registry import registry
from ruamel.yaml import YAML

import kalfa
from kalfa.api import check
from kalfa.config import load_surface, pack_tables, parse_sets
from kalfa.contract import Contract
from kalfa.describe import report
from kalfa.docs import render as render_docs
from kalfa.driver import recipe
from kalfa.recipe import recipe_text
from kalfa.std import STD_URIS
from kalfa.style import Style

ROOT = Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "examples"
GOLDEN = Path("tests") / "golden"
CONTRACT = ROOT / "src" / "kalfa" / "contract.yaml"
TOLERATED = ("source_missing", "weights_run_missing")
IGNORED = ("runs", "data", "*.parquet", "*.txt", "__pycache__")


def examples():
    return sorted(path.name for path in EXAMPLES.iterdir() if (path / "config.yaml").is_file())


def config_of(name):
    return f"examples/{name}/config.yaml"


def prepared_of(name):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        prepared = check([str(ROOT / config_of(name))])
    errors = [problem for problem in prepared.errors if problem.kind not in TOLERATED]
    if errors:
        raise SystemExit("\n".join(f"{name}: [{problem.kind}] {problem.message}" for problem in errors))
    return prepared


def dump_header(name):
    return (f"# Generated by kalfa {kalfa.__version__} (cirak {cirak.__version__}) from {config_of(name)}: "
            f"kalfa check --dump, the flow the\n"
            f"# contract of src/kalfa/contract.yaml opens for the driver document "
            f"tests/golden/recipes/{name}.recipe.yaml.\n"
            f"# Regenerate with: uv run python tools/regenerate.py dumps\n"
            f"# Sections: components (the recipe's component tables), blocks (spec and graph blocks as templates;\n"
            f"# the flow blocks are opened inside flow), flow (the expanded flow with every output written out;\n"
            f"# the comments are tezgah's resolution: implicit bindings, pattern matches, derived reads and "
            f"exports).\n")


def write_dumps():
    found = {}
    for name in examples():
        text = prepared_of(name).dump()
        if text is None:
            raise SystemExit(f"{name}: the flow could not be compiled")
        found[GOLDEN / "dumps" / f"{name}.flow.yaml"] = dump_header(name) + text
    return found


def recipe_header(name):
    return (f"# Generated by kalfa {kalfa.__version__} from {config_of(name)}: the driver document "
            f"kalfa.driver.recipe produces,\n"
            f"# the one the blocks of src/kalfa/contract.yaml open. Not written by hand; regenerate with:\n"
            f"#   uv run python tools/regenerate.py recipes\n")


def write_recipes():
    found = {}
    for name in examples():
        surface = load_surface([str(ROOT / config_of(name))])
        errors = [problem for problem in surface.problems if problem.severity == "error"]
        if errors:
            raise SystemExit("\n".join(f"{name}: [{problem.kind}] {problem.message}" for problem in errors))
        document = recipe(surface.data, aliases=surface.aliases)
        include = os.path.relpath(CONTRACT, ROOT / GOLDEN / "recipes")
        found[GOLDEN / "recipes" / f"{name}.recipe.yaml"] = (recipe_header(name) + f"include: [{include}]\n"
                                                             + recipe_text(document))
    return found


def write_docs():
    return {Path("DOCS.md"): render_docs()}


def signature_of(target):
    try:
        return str(inspect.signature(target))
    except (TypeError, ValueError):
        return ""


def plot_bus():
    return sorted(Contract.load().plot_bus)


def write_registry():
    legos = {}
    for uri in sorted(STD_URIS):
        entry = registry.lookup(uri)
        facts = {name: value for name, value in entry.facts.declared().items() if name not in ("alias", "kind")}
        legos[uri] = {"kind": entry.facts.kind, "alias": list(entry.facts.alias),
                      "signature": signature_of(registry.resolve(uri)), "facts": facts,
                      "description": entry.description}
    document = {"kinds": registry.kinds, "facts": registry.declared_facts, "legos": legos, "packs": pack_tables(),
                "plot_bus": plot_bus()}
    return {GOLDEN / "registry.json": json.dumps(document, indent=2, sort_keys=True) + "\n"}


def load_make_data(folder):
    spec = importlib.util.spec_from_file_location(f"make_data_{folder.name}", folder / "make_data.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def write_describe():
    found = {}
    with tempfile.TemporaryDirectory() as scratch:
        copy = Path(scratch) / "examples"
        shutil.copytree(EXAMPLES, copy, ignore=shutil.ignore_patterns(*IGNORED))
        previous = os.getcwd()
        try:
            for name in examples():
                folder = copy / name
                os.chdir(folder)
                load_make_data(folder).main()
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore")
                    prepared = check(["config.yaml"], parse_sets([]))
                found[GOLDEN / "describe" / f"{name}.txt"] = report(prepared, Style(False), None, None)
        finally:
            os.chdir(previous)
    return found


WRITERS = {"dumps": write_dumps, "recipes": write_recipes, "docs": write_docs, "registry": write_registry,
           "describe": write_describe}


def main(argv=None):
    parser = argparse.ArgumentParser(prog="regenerate", description="write the golden files of the tests")
    parser.add_argument("what", nargs="*", choices=list(WRITERS), help="which golden files; --all for every one")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--check", action="store_true", help="write nothing, report every file that would change")
    args = parser.parse_args(argv)
    chosen = list(WRITERS) if args.all or not args.what else args.what
    changed = []
    for name in chosen:
        for path, text in WRITERS[name]().items():
            target = ROOT / path
            if args.check:
                if not target.exists() or target.read_text() != text:
                    changed.append(path)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text)
            print(f"wrote {path}")
    if args.check:
        for path in changed:
            print(f"differs: {path}")
        print("every golden file is current" if not changed else f"{len(changed)} golden files differ")
        return 1 if changed else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
